/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EventoClick {
    }
    interface ImagenClick {
    }
    interface ListenerClick {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface EventoClickCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEventoClickElement;
}
declare global {
    interface HTMLEventoClickElement extends Components.EventoClick, HTMLStencilElement {
    }
    var HTMLEventoClickElement: {
        prototype: HTMLEventoClickElement;
        new (): HTMLEventoClickElement;
    };
    interface HTMLImagenClickElement extends Components.ImagenClick, HTMLStencilElement {
    }
    var HTMLImagenClickElement: {
        prototype: HTMLImagenClickElement;
        new (): HTMLImagenClickElement;
    };
    interface HTMLListenerClickElement extends Components.ListenerClick, HTMLStencilElement {
    }
    var HTMLListenerClickElement: {
        prototype: HTMLListenerClickElement;
        new (): HTMLListenerClickElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "evento-click": HTMLEventoClickElement;
        "imagen-click": HTMLImagenClickElement;
        "listener-click": HTMLListenerClickElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface EventoClick {
        "onCustomClick"?: (event: EventoClickCustomEvent<void>) => void;
    }
    interface ImagenClick {
    }
    interface ListenerClick {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "evento-click": EventoClick;
        "imagen-click": ImagenClick;
        "listener-click": ListenerClick;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "evento-click": LocalJSX.EventoClick & JSXBase.HTMLAttributes<HTMLEventoClickElement>;
            "imagen-click": LocalJSX.ImagenClick & JSXBase.HTMLAttributes<HTMLImagenClickElement>;
            "listener-click": LocalJSX.ListenerClick & JSXBase.HTMLAttributes<HTMLListenerClickElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
